const playing = [
  "Santorini",
  "Santorini App",
  "Dice Throne",
  "Dice Throne Adventures",
  "Steampunk Rally",
  "Steampunk Rally Fusion",
  "Super Motherload",
  "Brass: Birmingham",
  "Brass: Lancashire",
  "Radlands",
  "SKYRISE",
  "The Royal Game of Ur",
  "7 Wonders",
  "7 Wonders Duel",
  "Acropolis of Athens",
  "Agamemnon",
  "Elysium",
  "Corinth",
  "Lords of Hellas",
  "Oracle of Delphi",
  "Cyclades ",
  "Hoplite",
  "Poseidon's Kingdom",
  "Sid Meier's Civilization",
  "Sparta",
  "Through the Ages",
  "Zeus on the Loose",
  "Mythic Battles: Pantheon",
  "Deus",
  "Olympos",
  "Mythtopia",
  "Helios",
  "Poseidon",
  "Ancient Terrible Things",
  "Pantheon",
  "Hera And Zeus",
  "Fate Of The Elder Gods",
  "Risk: Godstorm",
  "Chez Greek",
  "Archipelago",
  "Forbidden Island",
  "Akrotiri",
  "Islebound",
  "Sleeping Gods",
  "History Of The World",
  "Peleppones",
  "Perikles",
  "Iliad",
  "Dixit: Odyssey",
  "Apples To Apples",
  "Gorilla Marketing",
  "Gods & Monsters",
  "Rise Of The Argonauts",
  "NyxQuest: Kindred Spirits",
  ];

const watching = [
    "Rahdo Runs Through",
    "The Undead Viking",
    "Watch It Played",
    "Tantrum House",
    "Man Vs. Meeple",
    "The Cardboard Kid",
    "Gaming With Edo",
    "Shut Up & Sit Down",
    "LoadingReadyRun",
    "Actualol",
    "No Pun Included",
    "Drive Thru Review",
    "The Game Boy Geek",
    "The Dice Tower",
    "Jon Gets Games",
    "Heavy Cardboard",
    "Roxley's YouTube Channel",
    "Board Game Revolution",
    "Geek & Sundry",
    "Meeple University",
    "Jason and the Argonauts",
    "Troy",
    "300",
    "Atlantis",
    "Clash of the Titans",
    "Wrath of the Titans",
    "The Odyssey",
    "Hercules",
    "Odissea",
    "Fury of Achilles",
    "My Big Fat Greek Wedding",
    "Grease",
    "Sinbad: Legend Of The Seven Seas",
  ];

module.exports = {
    playing: playing,
    watching: watching
}